version: "3.8"

services:
  golang_apigateway:
    image: mohiey/chatbuggo:latest
    environment:
      - HOST=
      - PORT=3001
      - HMAC_SECRET=cweu73he%sdj3.adkHdw.ijd3go3%cs
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=1
      - SIDEKIQ_REDIS_HOST=redis:6379
      - SIDEKIQ_REDIS_DB=0
      - SIDEKIQ_REDIS_POOLSIZE=10
      - SIDEKIQ_PROCESSID=1
    ports:
      - "3001:3001"
  rails_api:
    image: mohiey/chatbugrails:latest
    environment:
      DB_USERNAME: root
      DB_PASSWORD: my-secret-pw
      DB_HOST: db
      DB_PORT: "3306"
      HMAC_SECRET: cweu73he%sdj3.adkHdw.ijd3go3%cs
      REDIS_URL: redis://redis:6379
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  rails_workers:
    image: mohiey/chatbugrails:latest
    environment:
      DB_USERNAME: root
      DB_PASSWORD: my-secret-pw
      DB_HOST: db
      DB_PORT: "3306"
      HMAC_SECRET: cweu73he%sdj3.adkHdw.ijd3go3%cs
      REDIS_URL: redis://redis:6379
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      db:
        condition: service_healthy
    command: [ "bundle", "exec", "sidekiq" ]
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
  redis:
    image: redis
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      discovery.type: single-node
      cluster.name: elasticsearch-rails
      cluster.routing.allocation.disk.threshold_enabled: "false"
    ports:
      - "9200:9200"
